---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}

if (!require(knitr)) install.packages("knitr")
if (!require(pacman)) install.packages("pacman")
pkg_list <- c("tidyverse", "glue", "magrittr", "plotly", "moments", "emmeans", "conflicted", "gridExtra", "kableExtra", "rcompanion", "broom", "rstatix", "ggpubr", "Rmisc")

pacman::p_load(char = pkg_list) #update=TRUE

knitr::opts_chunk$set(
  warning = FALSE,
  echo = FALSE,
  message = FALSE,
  error=FALSE,
  cache = FALSE
)

options(scipen=999, digits=4)

alpha <- 0.05
set.seed(42)

initial.data <- "../data/initial.csv"

conflict_prefer("arrange", "plyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("rename", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("summarize", "dplyr")
conflict_prefer("layout", "plotly")

tabl <- function(data, title="Table caption") {
  kable(data, col.names=gsub("[.]", " ", names(data)), booktabs=T, align="c", digits=3, format.args=list(big.mark=",", scientific=FALSE), escape=F, caption=title, linesep=c("")) %>% 
    kable_styling(font_size = 10, latex_options = c("striped", "scale_down", "hold_position"), position = "left") %>%
    row_spec(0, background = "#d4dbde", bold = T, color = "#2b4894")
}
options(knitr.table.format = ifelse(knitr::is_latex_output(), "latex", "pandoc"), knitr.kable.NA = "")

hs.order <- c("1","2","3","4","5","6","7","8","9","10")
```

```{r results='hide'}
data.wide <- read_csv(initial.data) %>% 
  select(-X1) %>% 
  mutate(mode = ifelse(mode == "N", "NG", "G")) %>%
  rename("Condition" = mode, "Hotspot" = hotspot) %>%
  mutate(across(c(Hotspot, Condition), as.factor)) %T>% print

data.long <- data.wide %>%
  mutate(id = seq_along(Hotspot), .before = Hotspot) %>%
  pivot_longer(cols = "P1":"P4", names_to="Participant", names_transform = list(Participant = as.factor), values_to = "Time") %>%
  relocate(Participant, id, Condition, Hotspot, Time) %>%
  #mutate(Hotspot = factor(Hotspot, levels = hs.order)) %>%
  dplyr::arrange(Participant, id) %T>% print
```
***
# Wilcoxon
***

```{r}
data.long.wil <- data.long %>% dplyr::arrange(Participant, Hotspot, Condition) %T>% print
```

```{r}
wsrt1 <- wilcox.test(formula=Time ~ Condition, data=data.long.wil, paired=TRUE, alternative="two.sided", exact=FALSE, correct=FALSE)
wsrt1 %>% tidy
wsrt1$statistic
```

```{r}
G <- data.long.wil %>% filter(Condition == "G") %>% select(Time) %T>% print
NG <- data.long.wil %>% filter(Condition == "NG") %>% select(Time) %T>% print

wsrt2 <- wilcox.test(NG$Time, G$Time, paired=TRUE, alternative="two.sided", exact=FALSE, correct=FALSE)
wsrt2 %>% tidy
```

```{r}
wilcox_test(Time ~ Condition, data=data.long.wil, paired=TRUE, alternative="less")
```


```{r}
wrst.z <- wilcoxonZ(NG$Time, G$Time, paired = TRUE, digits = 3)
wrst.z
```

```{r}
#wrst.z / sqrt(nrow(NG))
data.long.wil %>% rstatix::wilcox_effsize(formula=Time ~ Condition, paired=TRUE, alternative="less")
```

```{r}
sign_test(Time ~ Condition, data=data.long.wil)
```


# Success:

```{r}
data.long.logit <- data.long %>% mutate(Success = ifelse(Time >= 120, 0, 1)) %T>% print
```

```{r}
tbl1 <- table(data.long.logit$Condition, data.long.logit$Success)
tbl1
```

```{r}
tbl2 <- prop.table(tbl1) %>% round(2)
tbl2
```

```{r}
chisq_test(tbl1)
```
***
# Graphics
***

```{r}
data.long %>% gghistogram(
  x = "Time",
  rug = T,
  add = "median",
  color = "Condition",
  fill = "Condition",
  alpha = 0.75,
  palette = c("#00AFBB", "#f48806"),
  bins = 20,
  xticks.by = 20,
  xlab = "Time to find hotspot",
  ylab = "Count",
  facet.by = "Condition"
)

ggsave("../res/img/hist.png", device = "png", dpi = 320)
```

```{r warnings=F}
data.pairwise <- data.long %>% 
  dplyr::arrange(Participant, Hotspot, desc(Condition)) %>%
  group_by(Participant, Hotspot) %>%
  summarize(Diff = -1*diff(Time)) %>%
  ungroup() %T>% print
```

```{r}
data.pairwise %>% gghistogram(
  x = "Diff",
  bins = 20,
  rug = T,
  color = "#0c8c1a",
  fill = "#0c8c1a",
  xlab = "Paired time-differences",
  ylab = "Count",
  xticks.by=20
)

ggsave("../res/img/hist_diff.png",
       device = "png",
       dpi = 320)
```

```{r warnings=T}
fig.full <- ggdotchart(
  data.long,
  x = "Hotspot",
  y = "Time",
  color = "Condition",
  #shape = "Condition",
  palette = c("#00AFBB", "#f48806"),
  add = "segments",
  add.params = list(color = "lightgray", size = 1.5),
  group = "Hotspot",
  dot.size = 4,
  #label = "Time",
  font.label = list(
    color = "white",
    size = 8,
    vjust = 0.5
  ),
  facet.by = "Participant",
  xlab = "Hotspot",
  ylab = "Time to find hotspot",
  ylim = c(0, 130),
  yticks.by = 20
) #+ scale_x_discrete(labels=hs.order)

fig.full
ggsave("../res/img/full.png", fig.full, device = "png", dpi=320)
```

```{r}
dat <- data.long %>% Rmisc::summarySE(measurevar="Time", groupvars=c("Condition", "Participant")) %>% print
pd <- position_dodge(0.3)

fig <- dat %>%
  ggplot(aes(x = Condition, y = Time, color = Participant)) + #group=1
  geom_line(position = pd) +
  geom_errorbar(aes(ymin = Time - se, ymax = Time + se), size = 0.9, width = 0.15, position = pd) +
  geom_point(aes(fill=Participant), shape=21, size=3.2, position = pd) +
  theme_classic() +
  theme(axis.text.x = element_text(size=12, color="black"),
        axis.text.y = element_text(size=12, color="black")) +
  labs(x="Guidance condition", y="Time to find hotspot", ylim=c(0,120))

fig
ggsave("../res/img/lines.png", device = "png", dpi=320)
#ggplotly(fig)
```

